---
# Installing the nginx server.
- name: Install the nginx server.
  ansible.builtin.dnf:
    name: nginx
    state: latest

# Starting and enabling the nginx service.
- name: Start and Enable the nginx service.
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

# Running the app-pre-req from common role.
- name: Run the app-pre-req from common role.
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req 

# Creating expense.conf file and configure the backend server host details inside it and copy this file to /etc/nginx/default.d/expense.conf
- name: Create expense.conf file and confire the backend server details and copy this file to /etc/nginx/default.d/expense.conf.
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - Restart Nginx Service

# # Restarting the nginx service.
# - name: Restart nginx service.
#   ansible.builtin.service:
#     name: nginx
#     state: started
...